import json
import os
import time

# Import functions from pipeline modules
from exe_analyzer import run_exercise_analysis
from report_analyzer import analyze_medical_report, MedicalReportAnalyzer
from summarizer import generate_patient_summary

def main():
    patient_id = "patient123"
    pdf_report_path = "Elbow_fractures.pdf"
    output_dir = "output"
    
    os.makedirs(output_dir, exist_ok=True)
    
    print("="*60)
    print("PHYSIO AI PIPELINE INITIATED")
    print("="*60)
    
    # -----------------------------
    # Step 1: Exercise Analysis (Webcam)
    # -----------------------------
    print("\n[1/4] Starting Exercise Pose Analysis...")
    print("Please stand clearly in front of the webcam.")
    time.sleep(2)  # Give user a moment to ready
    
    # Run the exercise evaluation process
    print("Capturing 15-second tracking interval...")
    anomalies = run_exercise_analysis(exercise_name="T_pose", threshold=10.0, monitor_time=15)
    
    exe_anomalies_file = os.path.join(output_dir, f"{patient_id}_T_pose_anomalies.json")
    with open(exe_anomalies_file, "w") as f:
        json.dump(anomalies, f, indent=4)
        
    print(f"✓ Pose analysis complete. Data saved to {exe_anomalies_file}")
    
    # -----------------------------
    # Step 2: Medical Report Analysis
    # -----------------------------
    print("\n[2/4] Analyzing Medical PDF Report...")
    try:
        report_result = analyze_medical_report(pdf_report_path, patient_id=patient_id)
        
        # Pydantic support
        if hasattr(report_result, "model_dump"):
            report_dict = report_result.model_dump()
        elif hasattr(report_result, "dict"):
            report_dict = report_result.dict()
        else:
            report_dict = report_result
            
        report_analysis_file = os.path.join(output_dir, f"{patient_id}_medical_report_analysis.json")
        print(f"✓ Report analysis complete. Data saved to {report_analysis_file}")
    except Exception as e:
        print(f"❌ Failed to analyze medical report: {e}")
        return

    # -----------------------------
    # Step 3: Interactive Questionnaire
    # -----------------------------
    print("\n[3/4] Gathering Patient Context (Follow-Up Questions)...")
    questions = report_dict.get("follow_up_questions", [])
    
    user_answers = {}
    if questions:
        print("\nThe AI Agent has some follow-up questions based on your medical report.")
        print("Please answer the following (type your response and press Enter):")
        
        for idx, question in enumerate(questions, 1):
            print(f"\nQ{idx}: {question}")
            answer = input("Your Answer: ").strip()
            # If the user just hits Enter without typing, record "No answer provided"
            user_answers[question] = answer if answer else "No answer provided"
            
        # Save answers to JSON for the summarizer LLM context
        user_answers_file = os.path.join(output_dir, f"{patient_id}_user_answers.json")
        with open(user_answers_file, "w") as f:
            json.dump(user_answers, f, indent=4)
        print(f"✓ Feedback collected. Answers saved to {user_answers_file}")
    else:
        print("✓ No follow-up questions generated by the AI.")
        user_answers_file = None

    # -----------------------------
    # Step 4: Final AI Summary Generation
    # -----------------------------
    print("\n[4/4] Generating Final Patient Summary...")
    print("Synthesizing physical and anatomical data...")
    
    try:
        final_summary = generate_patient_summary(
            patient_id=patient_id,
            exercise_anomalies_file=exe_anomalies_file,
            report_analysis_file=report_analysis_file,
            joint_analysis_file=None, # Defaults to exercise anomalies
            user_answers_file=user_answers_file
        )
        
        print("\n" + "="*60)
        print("PIPELINE COMPLETE - FINAL SUMMARY")
        print("="*60)
        print(final_summary.summary)
        
        print("\n--- Key Findings ---")
        for finding in final_summary.key_findings:
            print(f"- {finding}")
            
        print("\n--- Recommendations ---")
        for rec in final_summary.recommendations:
            print(f"- {rec}")
            
        print("\n--- Risk Factors ---")
        for risk in final_summary.risk_factors:
            print(f"- {risk}")
            
    except Exception as e:
         print(f"❌ Failed to generate final summary: {e}")

if __name__ == "__main__":
    main()
